homeaudit(

	[
		{
			"logoURL":"images/sample/eai_logo_1.png",
			"score":99,
			"state":"up",
			"name":"wistron_KS"
		},
		{
			"logoURL":"images/sample/eai_logo_1.png",
			"score":95,
			"state":"up",
			"name":"wistron_ZS"
		},
		{
			"logoURL":"images/sample/eai_logo_2.png",
			"score":94,
			"state":"down",
			"name":"Compal"
		},
		{
			"logoURL":"images/sample/eai_logo_3.png",
			"score":85,
			"state":null,
			"name":"Quanta"
		},
		{
			"logoURL":"images/sample/eai_logo_4.png",
			"score":90,
			"state":"up",
			"name":"Bitand"
		},
		{
			"logoURL":"images/sample/eai_logo_5.png",
			"score":50,
			"state":"down",
			"name":"LCFC"
		}
	]
)